### ISSUE TITLE
Issue with RequireJS config for multiple require()'s

### ISSUE THREAD

**Issue by bashmach** [bluzphp/skeleton#131]
В очередной раз поймал ошибку подключения скриптов через requirejs.
Вот, например, эта ошибка на странице примера с Backbone в чистом skeleton-е.
![bluz-require-problem](https://f.cloud.github.com/assets/333910/1732595/e9b5d4fe-6321-11e3-8838-f418fff8b716.png)
Причина заключается в том, что на странице используется 2 точки входа в require, а конфиг только в js/config.js. Об этом предупреждается и в документации (http://requirejs.org/docs/api.html#data-main). 
Т.е. в этом конкретном случае ошибка возникает из-за того, что подключение 'bootstrap, jquery, backbone' в шаблоне test/views/backbone.phtml происходит перед выполнением require.config().

**Comment by AntonShevchuk** [comment]
Данный issue уже давно не актуален, RequireJS и config подключаются до любых вызовов require()
