### ISSUE TITLE
Create Contact Us Module

### ISSUE THREAD

**Issue by AntonShevchuk** [bluzphp/skeleton#183]
Форма для гостя:
- Name
- Email
- Message
- Captcha

Форма для пользователя:
- Message

... данный функционал (поля и т.п.) будет расширяться разработчиком в зависимости от требований заказчика

Функционал администратора:
- Grid
- Mark as read
- Mark as answered
- Reply

**Comment by bashmach** [comment]
Привет!
Какой статус у таска?

**Comment by AntonShevchuk** [comment]
В разработке, надо уточнить у Коли

**Comment by AntonShevchuk** [comment]
Функционал, который требует ревью и переноса:

https://github.com/kosheleva/skeleton/tree/master/application/models/ContactUs
https://github.com/kosheleva/skeleton/tree/master/application/modules/contact-us
https://github.com/kosheleva/skeleton/tree/master/public/js/contactUs

**Comment by AntonShevchuk** [comment]
Отдельный модуль - https://github.com/bluzphp/module-contact-us
