### ISSUE TITLE
Create Doker configuration

### ISSUE THREAD

**Issue by AntonShevchuk** [bluzphp/skeleton#205]
Понравилось как сие сделано тут - https://github.com/nazar-pc/CleverStyle-CMS/tree/master/docker

**Comment by bashmach** [comment]
Привет!
Сделал форк laravel/homestead со скелетоном на борту - https://github.com/bashmach/bluz-on-homestead и возможностью использовать под проект отдельную виртуалку.
Совсем не Docker конечно, но может подойти под цели, которые, судя по всему, были поставлены при создании данного таска.

**Comment by loginwashere** [comment]
Раньше с docker не работал, но стало интересно его попробовать.
Пока что завел под это отдельный репозиторий https://github.com/loginwashere/bluz-docker-experiments. 
Добавил там описание контейнера по типу как в ссылке которую привел @AntonShevchuk. 
Теперь в планах попробовать docker-compose и вынести nginx и mysql в отдельные контейнеры и возможно добавить контейнер для данных mysql.

**Comment by loginwashere** [comment]
Попробовал вынести некоторые сервисы в другие контейнеры (nginx, mysql и данные mysql) и вот что получилось https://github.com/loginwashere/skeleton/tree/addDockerSupport/docker.

**Comment by loginwashere** [comment]
Еще вот такую штуку нашел https://github.com/phundament/app.
Она для yii, но интересно посмотреть как они делали

**Comment by yuklia** [comment]
сетаплю докер конфигурацию для блюза. проблема в структуре ddl . для mysql 5.7.12 по умолчанию включен строгий режим (NO_ZERO_DATE). несуществующие даты уже не пройдут updated TIMESTAMP DEFAULT '0000-00-00 00:00:00' NOT NULL.
шо робить?
1 сетапить на 5.6 тогда поправить доку на гитхабе
2 выключить строгий режим в конфигурации имеджа
3 писать поддержку настройки режимов как в laravel
4 засетапить дефолтное для TIMESTAMP - CURRENT_TIMESTAMP

пример как в ларавеле
'connections' => [
        'mysql' => [
           // Игнорировать этот ключ, полагаться  на ключ strict
            'modes' => null,
           // Отключить принудительно все режимы, переопределяя  настройку strict
            'modes' => [],
           // Принудительно включить только указанные  режимы, переопределяя  настройку strict
            'modes' => [
                'STRICT_TRANS_TABLES',
                'ONLY_FULL_GROUP_BY',
            ],
        ]
    ]

**Comment by AntonShevchuk** [comment]
Давай попробуем насетапить дефолтное `CURRENT_TIMESTAMP`

**Comment by yuklia** [comment]
ок
