### ISSUE TITLE
Create Modules structure

### ISSUE THREAD

**Issue by AntonShevchuk** [bluzphp/skeleton#39]
Необходимо продумать систему для разворачивания произвольных модулей. В идеале, создаём проект на базе composer, проставляем зависимости от skeleton'a и лишь необходимых модулей (между собой модули разруливают зависимости уже на уровне composer'а).

**Comment by bashmach** [comment]
А под модулем мы ж подразумеваем как контроллеры с вьюхами, так и модели или, например, всякую статику, связанную с этим модулем, так ведь?

**Comment by AntonShevchuk** [comment]
Вот насчёт статики, я не уверен, хотя в идеале - да, устанавливаем модуль и получаем весь рабочий функционал

**Comment by AntonShevchuk** [comment]
Надо в wiki сделать описание структуры модулей и процедуры их сетапа

**Comment by AntonShevchuk** [comment]
Создан репозиторий плагина bluzphp/composer-pugin, запрос на документацию добавлен
https://github.com/bluzphp/composer-plugin/issues/4
